# Possible Issues:
#
# .gradlw permission denied:
# git update-index --chmod=+x gradlew //http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied

language: android
jdk: oraclejdk8

android:

  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - openssl aes-256-cbc -K $encrypted_c3767de358ec_key -iv $encrypted_c3767de358ec_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

script:
    - ./gradlew clean
    - ./gradlew assemble --stacktrace
    - ./gradlew lint --stacktrace

deploy:
  - provider: script
    script: ./gradlew install bintrayUpload --info
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "rNHcudueUGQXYSipzXU0DjebDrvSAHU3hlH8Z6YExqFOOL+yUTdUE74Qh3V85W73al5i5g1sQrdO63zGpHAXhK/LQx2w6LjtLxgjF2+dDByD+xm8P0BwpPr6GWJ/qisS9M9betp1K61MxXDeBHLUhCQ383sNXNeVa4cZCXtMB8W9ojAjpJzaOub3SGRg327p0ZTc4FqiIm4EJjK2eQWHEbLvBkC4h/qmB0rC0PgmROazfYVSDpyqaqcBYNDiHnpM3QN37QukTLJIwR8QxIdvqnv9zuhW6IlJN2c0NE1htMJMxN/6VQ+EAhkqrrzkSQb2U5jy5uML5is0gu4OCHvK6vxMAgeHMPnlG86WQDsZRxrXtCxEj1AihRIBfZlMveCCdBPXvWUPzK38k8a7FdUiYsCzAcy0ck5UiQqNWxQ9t0vwJsfWkjI1gDZvBvzmZYyYSgIjNuT2TYF9vZpsmwZDeoIls8ruLBXIunb0kAsxBhJBIOrYgfqj+Wejri0BMJVfPwbCAnEibM1fdqK/HZmJxGvfJJkrx1khwct8R+cYlha3L65wOrrj03G2n/IqTZCrW2oCfCVcTupVlncH+95kgMhZdDg66S0pnfXQYUdnB4n1rz0uHbpVa0aaiR8jm3C0i4ioSvLKWmLlArcOP5txk4if2WvDXTwt3XSpMe1bsLI="
    file:
     - 'DaliTestApp/build/outputs/apk/DaliTestApp-release.apk'
     - 'dali/build/outputs/aar/dali-release.aar'
    skip_cleanup: true
    on:
      branch: master
      tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

notifications:
  slack:
    secure: "dOwS86KBc/5+cOG7qkpkqemwhRafca9VOLtXTcgUaO/Z/Th37CddueOn0AhMSUzGsiqTm8vDCPDnnF1MsOxphjvBcFjyMhDVXAobi4Z3WKUDb6R6BdgOQUoTBV34naFa8Ti7S1zKZtjBlAaf+f6RLl2eAf1REJrYKSK0iJ2uDiUg/L02WeFPBcoVRCh5o/oCOJIe0fPKAV2n/WeODvIJrJqPcfnsWP98YlBcohI44z3/xKS+nQsSmrvBH2O+y3wX25luLTEZIwq2CkJM11AQeitjbA/qdEpVPQg7X+MyQPOI605hD2MFesxoFN+hUYEZYWR3CYZRFCGU+2cLXjgi1+zOTR7L1Lwv9jB+PiohsYE9zhncM2JCeOH7oPNgLV6Ad8HA+PiR7wXZAAxVA00H3zN0/OSTVTklzsf4K02rFPkJxxkAgXMfMlDlp2t07cvNiguoc9qGQDP99iRjbJkpwcuN+spmRZY6ARcOsfc49Xkm27oI3NXbQLEL5Dhplrge/fl/m2kAr9xolOW32dBFljK39hlhPKF7/f/GZAQ+23l6TzjRptxqbz8xjrCAczOepQxskjGgEMbthqGfPFrRRSD846XJpvMCVik3YgVuISZzplXMqJl1IUe4/CSu8jiLrXnnkTOtpzB2xRluLsnpQLcKNSkOVUdi63drbSLncIE="
  email: false